# Generated by Django 4.0.3 on 2022-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.CharField(max_length=50)),
                ('encText', models.TextField(blank=True, null=True)),
                ('keys', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
